version: '3.7'

services:
    rustrank-frontend:
        container_name: rustrank-frontend
        command: bash -c 'npm run start'
        ports: 
            - 443:3000
        volumes:
            - .:/app
            - /app/node_modules
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
